# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
    - name: Ponicode DogString: Automatic AI-based Docstring generation
  # You may pin to the exact commit or the version.
  # uses: ponicode/dogstring-action@0d2a9acd2cff787c524e3573ddb2131657b41cd3
      uses: ponicode/dogstring-action@v0.1.2-beta
        with:
    # Path of repo to generate docstrings for
         repo_path: # default is ./https://github.com/NaveenBandarage
    # Boolean: choose using the action on all the repository or just on the last commit
         all_repo: 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install argparse
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
